@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System(vegvesen, "Statens Vegvesen")

System_Boundary(c1, "Retrieve XML") {
    Container(retriever, "Parser", "Rust, Diesel, Serde", "Parse XML and convert to JSON")
}

System(microservice, "weather_web", "actix-web")

Rel(vegvesen, retriever, "Uses", "https")
Rel(retriever, microservice, "Uses", "http port 8080")

@enduml